'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const root=__dirname;
const herdr=require('./lib/herdr');
require('./lib/pstree').query=()=>null;
const calls=[];let now=0;let launches=0;
herdr.snapshot=()=>({workspaces:[{number:1,label:'x',workspace_id:'w1'}]});
herdr.tabList=()=>[{number:1,tab_id:'w1:t1'}];
herdr.paneList=()=>[{pane_id:'w1:p1',tab_id:'w1:t1'},{pane_id:'w1:p2',tab_id:'w1:t1'}];
herdr.processInfo=(pid)=>({shell_pid:1,foreground_processes:[{pid:1}],foreground_process_group_id:1});
herdr.runInPane=(pid,cmd)=>{calls.push({pid,cmd,at:now});launches++;return {code:0};};
herdr.agentList=()=>calls.map(x=>({pane_id:x.pid,agent:'opencode',agent_status:'idle'}));
const restore=require('./lib/restore');
const pane=(id)=>({pane_id:id,agent:{name:'opencode',session:{value:'ses_'+id}}});
const model={tool:'herdr-resurrect',workspaces:[{number:1,label:'x',tabs:[{number:1,panes:[pane('a'),pane('b')]}]}]};
restore.restore(model,{mode:'rehydrate',startupDelayMs:10000,clock:()=>now,sleep:(ms)=>{now+=ms;}});
assert.equal(calls[0].cmd,'opencode --session ses_a');
assert.equal(calls[1].cmd,'opencode --session ses_b');
assert.ok(calls[1].at-calls[0].at>=10000,JSON.stringify(calls));
console.log('PASS: explicit session IDs and >=10 second sequential launch spacing');
